# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b431dd10fbc7d9070c18a5a339ec42bb781a7e631937b9d175407eb03437d87e56346835ac125ddff7a7ef76c278e840616605d889a25726cc6727650a45e447

test:
  secret_key_base: 586b1d84757b6b20ac211f00d6051fb0dcc4bbf9f701ad81fc5459f9c6499d1b6439ee4df845d51d578560a8ab400d2aaccb58f5bbbb7e8fb7bc15a95e64c66c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
